### ISSUE TITLE
scbd插件无法自动同步历史数据

### ISSUE THREAD

**Issue by 20051111** [alex3236/ScarpetScripts#2]
部分scbd选项无法同步历史数据，可以同步的有飞行行走在线时间，其他无法同步

**Comment by 20051111** [comment]
已解决，好像需要重进游戏

**Comment by alex3236** [comment]
是的，只会在进游戏时同步，且每个玩家只同步一次。不然你服得卡死（

**Comment by 20051111** [comment]
有办法从后台手动同步数据给插件吗

**Comment by alex3236** [comment]
> 有办法从后台手动同步数据给插件吗

无法获取服务器不在线的玩家
